# Generated by Django 3.2.13 on 2022-04-17 16:23

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_donation_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
